### ISSUE TITLE
data url paths

### ISSUE THREAD

**Issue by tsladecek** [genpat-it/spread#5]
Just a minor feature request. Currently the url paths start with a slash. This prohibits (as far as I know) the use of absolute paths to a file. My use case:

- I deploy the a app to a kubernetes cluster and mount a volume with my data containing the newick trees and metadata files at container path `/data`.  However when I try to open a new tree via the url parameter `?tree=...`, the path is not working. It is working with the example given in the README file `?tree=/datasets/test/tree.nwk`.

Quick fix from my side is to mount the volume to the app dir, however I would prefer to have it at the root dir

**Comment by andreaderuvo** [comment]
Here are three possible solutions that come to mind (not tested):

1. Using symbolic links to include `/data` into `/spread`

2. Update provided `server.js` to serve also `/data` folder. Something like:
`
app.use('/data', express.static(path.resolve(__dirname, '../data')));
`

_(We can enhance this by using an input parameter to mount folders dynamically under the `/spread` endpoint.)_

3. Using an additional webserver to serve `/data` files (example http://localhost:9000) over HTTP, use the `&withProxy` query string parameter and point to the exposed resources using absolute URLs (example http://localhost:9000/tree.nwk)

Keep me updated, and if you come across a simpler strategy, we can implement it.

**Comment by tsladecek** [comment]
Thank you for the suggestions, I will figure something out. I forgot that this is a client side application :sweat_smile: 

I think that the second option might be the best (although requires work from your side). Maybe this can be an optional parameter to the application (via env variable?). I am just guessing. Thank you very much for the quick replies. It is very appreciated!
